backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - label: "About Section"
        name: "about"
        file: "about.md"
        fields:
          - { label: "About Text", name: "body", widget: "markdown" }
