backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "about"
    label: "About Section"
    files:
      - file: "index.html"
        label: "About Content"
        name: "about_content"
        fields:
          - label: "About Text"
            name: "body"
            widget: "markdown"
