backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "about"
    label: "About Section"
    files:
      - file: "index.html"
        label: "About Us"
        name: "about_us"
        fields:
          - { label: "About Text", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery Images"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
